version: '3.8'

services:
  app:
    build: .
    environment:
      - DATABASE_URL=postgresql://prosalemanager:prosalepassword@db:5432/prosaledatabase
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=prosalemanager
      - DB_PASSWORD=prosalepassword
      - DB_NAME=prosaledatabase
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=prosalemanager
      - POSTGRES_PASSWORD=prosalepassword
      - POSTGRES_DB=prosaledatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prosalemanager -d prosaledatabase"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data: 